export const STAFF_PROFILES = [
  {
    staffId: "AD001",
    roleId: "administrator",
    emergencyCode: "918273",
    pin: "987654",
    initials: "SA",
    shortName: "Admin",
    name: "SmartCare Administrator",
    role: "Administrator",
    department: "Health Information Security",
    ward: "All Units",
    shift: "All Shifts",
    accessLevel: "Hospital-level administrative access",
  },
  {
    staffId: "DR001",
    roleId: "attending_doctor",
    emergencyCode: "482916",
    pin: "123456",
    initials: "DA",
    shortName: "Dr.",
    name: "Dr. Adaeze Okonkwo",
    role: "Attending Doctor",
    department: "Internal Medicine",
    ward: "Internal Medicine",
    shift: "Day Shift",
    accessLevel: "Full clinical access",
  },
  {
    staffId: "N8002",
    roleId: "nurse",
    emergencyCode: "739641",
    pin: "246810",
    initials: "NE",
    shortName: "Nurse",
    name: "Nurse Emeka Nwosu",
    role: "Nurse",
    department: "Ward B",
    ward: "Ward B",
    shift: "Day Shift",
    accessLevel: "Ward-limited clinical access",
  },
  {
    staffId: "RC003",
    roleId: "records_clerk",
    emergencyCode: "651204",
    pin: "135790",
    initials: "CE",
    shortName: "Clerk",
    name: "Chioma Eze",
    role: "Records Clerk",
    department: "Medical Records",
    ward: "Medical Records",
    shift: "Day Shift",
    accessLevel: "Demographic access only",
  },
  {
    staffId: "LD004",
    roleId: "visiting_locum_doctor",
    emergencyCode: "415687",
    pin: "112233",
    initials: "LO",
    shortName: "Locum",
    name: "Dr. Louise Okafor",
    role: "Visiting/Locum Doctor",
    department: "Surgery",
    ward: "Surgery",
    shift: "Night Shift",
    accessLevel: "Time-boxed clinical access",
  },
  {
    staffId: "LP005",
    roleId: "lab_pharmacy_staff",
    emergencyCode: "338421",
    pin: "654321",
    initials: "PB",
    shortName: "Lab",
    name: "Pharm. Blessing Ogu",
    role: "Lab/Pharmacy Staff",
    department: "Laboratory & Pharmacy",
    ward: "Pharmacy",
    shift: "Day Shift",
    accessLevel: "Order-relevant access only",
  },
];

export const ROLE_DEFINITIONS = [
  {
    id: "administrator",
    name: "Administrator",
    description: "Hospital-level security and staff assignment oversight.",
    permissions: [
      "view_patients",
      "view_all_patients",
      "view_staff",
      "view_staff_directory",
      "manage_roles",
      "assign_roles",
      "manage_assignments",
      "view_patient_assignments",
      "manage_emergency_access",
      "view_audit_logs",
      "view_security_alerts",
      "export_audit_logs",
      "view_my_patients",
      "view_own_access",
    ],
    protected: true,
  },
  {
    id: "attending_doctor",
    name: "Attending Doctor",
    description: "Senior physician with case-level and ward oversight.",
    permissions: [
      "view_patients",
      "view_all_patients",
      "edit_patients",
      "view_my_patients",
      "view_own_access",
      "manage_emergency_access",
    ],
    protected: true,
  },
  {
    id: "nurse",
    name: "Nurse",
    description: "Ward-based bedside clinical access for assigned patients.",
    permissions: [
      "view_patients",
      "edit_patients",
      "view_my_patients",
      "view_own_access",
      "manage_emergency_access",
    ],
    protected: true,
  },
  {
    id: "records_clerk",
    name: "Records Clerk",
    description: "Demographic and records access without diagnostic or sensitive data.",
    permissions: [
      "view_patients",
      "view_own_access",
    ],
    protected: true,
  },
  {
    id: "visiting_locum_doctor",
    name: "Visiting/Locum Doctor",
    description: "Time-boxed doctor access within rostered hours and approved scope.",
    permissions: [
      "view_patients",
      "edit_patients",
      "view_my_patients",
      "view_own_access",
      "manage_emergency_access",
    ],
    protected: true,
  },
  {
    id: "lab_pharmacy_staff",
    name: "Lab/Pharmacy Staff",
    description: "Order-relevant access scoped to laboratory and pharmacy tasks.",
    permissions: [
      "view_patients",
      "view_own_access",
    ],
    protected: true,
  },
];

export const PATIENT_ASSIGNMENTS = [
  {
    id: "assignment-1",
    patientId: "PT-000184",
    staffId: "N8002",
    staffName: "Nurse Emeka Nwosu",
    assignmentType: "Primary Nurse",
    ward: "Ward B",
    startDate: "2026-09-01",
    status: "Active",
  },
  {
    id: "assignment-2",
    patientId: "PT-2024-0561",
    staffId: "DR001",
    staffName: "Dr. Adaeze Okonkwo",
    assignmentType: "Attending Doctor",
    ward: "Maternity",
    startDate: "2026-09-03",
    status: "Active",
  },
  {
    id: "assignment-3",
    patientId: "PT-000184",
    staffId: "DR001",
    staffName: "Dr. Adaeze Okonkwo",
    assignmentType: "Attending Doctor",
    ward: "Ward B",
    startDate: "2026-09-01",
    status: "Active",
  },
];

export const PATIENTS = [
  {
    id: "PT-000184",
    patientNumber: "PT-000184",
    initials: "FA",
    name: "Fatima Abdullahi",
    age: 34,
    gender: "Female",
    ward: "Ward B",
    status: "Active",
    note: "Sickle cell care plan updated today",
    scope: "Out of scope",
    tone: "warning",
    demographics: {
      dob: "1988-01-17",
      address: "3 Enugu Crescent, Abuja",
      phone: "+234-809-777-0344",
      nextOfKin: "Amina Abdullahi",
    },
    diagnosis: [
      "Sickle cell disease with acute pain episode",
      "Previous vaso-occlusive crisis",
    ],
    medications: [
      { name: "Hydroxyurea", dose: "500 mg", schedule: "Once daily" },
      { name: "Paracetamol", dose: "500 mg", schedule: "As needed" },
    ],
    labs: [
      { label: "Hemoglobin", value: "8.2 g/dL", updated: "Today" },
      { label: "WBC", value: "11.2 x10^9/L", updated: "Today" },
    ],
    sensitiveFields: {
      hivStatus: "Positive",
      mentalHealth: "Stable - supportive counselling",
      genotype: "HbSS",
    },
  },
  {
    id: "PT-2024-0561",
    patientNumber: "PT-2024-0561",
    initials: "NN",
    name: "Ngozi Nnadi",
    age: 25,
    gender: "Female",
    ward: "Maternity",
    status: "Active",
    note: "Routine observation",
    scope: "In scope",
    tone: "green",
    demographics: {
      dob: "2001-07-08",
      address: "5 Igbinedion Road, Lagos",
      phone: "+234-803-555-0143",
      nextOfKin: "Musa Nnadi",
    },
    diagnosis: ["Routine postnatal monitoring"],
    medications: [
      { name: "Folic acid", dose: "5 mg", schedule: "Once daily" },
    ],
    labs: [
      { label: "Hemoglobin", value: "11.5 g/dL", updated: "Today" },
    ],
    sensitiveFields: {
      hivStatus: "Negative",
      mentalHealth: "No concerns",
      genotype: "AA",
    },
  },
];

export const AUDIT_EVENTS = [
  {
    id: 1,
    date: "12/09/2026",
    time: "19:36",
    actor: "Nurse",
    actorFullName: "Nurse Emeka Nwosu",
    actorId: "N8002",
    role: "NURSE",
    action: "Field accessed",
    field: "Allergies",
    target: "Fatima Abdullahi",
    ip: "192.168.1.50",
    eventId: "EVT320",
    hash: "7a1f32e14a91d4d47a7f32d47a7f32d4",
    prevHash: "1233d4432033034c1233d4432b3f...",
    chainOk: true,
  },
  {
    id: 2,
    date: "12/09/2026",
    time: "19:36",
    actor: "Nurse",
    actorFullName: "Nurse Emeka Nwosu",
    actorId: "N8002",
    role: "NURSE",
    action: "Viewed record",
    field: null,
    target: "Fatima Abdullahi",
    ip: "192.168.1.50",
    eventId: "EVT321",
    hash: "9b2e43f25b02e5e58b8f43e58b8f43e5",
    prevHash: "7a1f32e14a91d4d47a7f32d47a7f32d4",
    chainOk: true,
  },
  {
    id: 9,
    date: "08/09/2026",
    time: "08:43",
    actor: "Dr.",
    actorFullName: "Dr. Adaeze Okonkwo",
    actorId: "DR001",
    role: "ATTENDING_DOCTOR",
    action: "Viewed record",
    field: null,
    target: "Fatima Abdullahi",
    ip: "192.168.1.12",
    eventId: "EVT200",
    hash: "0295ba692c795a2c25f5ba2c25f5ba69",
    prevHash: "f184a9581b68419b14e4a9b14e4a958",
    chainOk: false,
  },
];

export const ROLE_PERMISSION_MATRIX = [
  { label: "Demographics", administrator: true, doctor: true, nurse: true, records: true, locum: true, lab: false },
  { label: "Vitals", administrator: true, doctor: true, nurse: true, records: false, locum: true, lab: false },
  { label: "Medications", administrator: true, doctor: true, nurse: true, records: false, locum: true, lab: false },
  { label: "Allergies", administrator: true, doctor: true, nurse: true, records: false, locum: true, lab: false },
  { label: "Clinical Notes", administrator: true, doctor: true, nurse: true, records: false, locum: true, lab: false },
  { label: "HIV Status", administrator: true, doctor: true, nurse: false, records: false, locum: false, lab: false },
  { label: "Mental Health Notes", administrator: true, doctor: true, nurse: false, records: false, locum: false, lab: false },
  { label: "Genotype / Blood Group", administrator: true, doctor: true, nurse: false, records: false, locum: false, lab: false },
];
