export const STAFF_PROFILES = [
  {
    staffId: "DR001",
    roleId: "attending_doctor",
    emergencyCode: "482916",
    pin: "123456",
    initials: "DA",
    shortName: "Dr.",
    name: "Dr. Adaeze Okonkwo",
    role: "Attending Doctor",
    department: "Internal Medicine",
    ward: "Internal Medicine",
    shift: "Day Shift",
    accessLevel: "Full clinical access",
  },
  {
    staffId: "N8002",
    roleId: "nurse",
    emergencyCode: "739641",
    pin: "246810",
    initials: "NE",
    shortName: "Nurse",
    name: "Nurse Emeka Nwosu",
    role: "Nurse",
    department: "Ward B",
    ward: "Ward B",
    shift: "Day Shift",
    accessLevel: "Ward-limited clinical access",
  },
  {
    staffId: "RC003",
    roleId: "records_clerk",
    emergencyCode: "651204",
    pin: "135790",
    initials: "CE",
    shortName: "Clerk",
    name: "Chioma Eze",
    role: "Records Clerk",
    department: "Medical Records",
    ward: "Medical Records",
    shift: "Day Shift",
    accessLevel: "Demographic access only",
  },
];

export const ROLE_DEFINITIONS = [
  {
    id: "attending_doctor",
    name: "Attending Doctor",
    description: "Senior physician with full clinical access.",
    permissions: [
      "view_patients",
      "edit_patients",
      "delete_patients",
      "view_audit_logs",
      "export_audit_logs",
      "view_staff",
      "manage_roles",
      "assign_roles",
      "view_roles",
      "edit_roles",
    ],
    protected: true,
  },
  {
    id: "nurse",
    name: "Nurse",
    description: "Ward-based clinical access for patient care.",
    permissions: [
      "view_patients",
      "edit_patients",
      "view_audit_logs",
      "view_roles",
    ],
    protected: true,
  },
  {
    id: "records_clerk",
    name: "Records Clerk",
    description: "Demographic and records access without clinical notes.",
    permissions: [
      "view_patients",
      "view_roles",
      "view_audit_logs",
      "create_staff",
    ],
    protected: true,
  },
  {
    id: "it_administrator",
    name: "IT Administrator",
    description: "System maintenance and administrative support access.",
    permissions: [
      "view_staff",
      "view_roles",
      "manage_roles",
      "assign_roles",
      "export_audit_logs",
    ],
    protected: false,
  },
  {
    id: "intern",
    name: "Intern",
    description: "Supervised trainee access.",
    permissions: [
      "view_patients",
      "view_roles",
    ],
    protected: false,
  },
];

export const PATIENTS = [
  {
    id: "PT-000184",
    patientNumber: "PT-000184",
    initials: "FA",
    name: "Fatima Abdullahi",
    age: 34,
    gender: "Female",
    ward: "Ward B",
    status: "Active",
    note: "Sickle cell care plan updated today",
    scope: "Out of scope",
    tone: "warning",
    demographics: {
      dob: "1988-01-17",
      address: "3 Enugu Crescent, Abuja",
      phone: "+234-809-777-0344",
      nextOfKin: "Amina Abdullahi",
    },
    diagnosis: [
      "Sickle cell disease with acute pain episode",
      "Previous vaso-occlusive crisis",
    ],
    medications: [
      { name: "Hydroxyurea", dose: "500 mg", schedule: "Once daily" },
      { name: "Paracetamol", dose: "500 mg", schedule: "As needed" },
    ],
    labs: [
      { label: "Hemoglobin", value: "8.2 g/dL", updated: "Today" },
      { label: "WBC", value: "11.2 x10^9/L", updated: "Today" },
    ],
    sensitiveFields: {
      hivStatus: "Positive",
      mentalHealth: "Stable - supportive counselling",
      genotype: "HbSS",
    },
  },
  {
    id: "PT-2024-0561",
    patientNumber: "PT-2024-0561",
    initials: "NN",
    name: "Ngozi Nnadi",
    age: 25,
    gender: "Female",
    ward: "Maternity",
    status: "Active",
    note: "Routine observation",
    scope: "In scope",
    tone: "green",
    demographics: {
      dob: "2001-07-08",
      address: "5 Igbinedion Road, Lagos",
      phone: "+234-803-555-0143",
      nextOfKin: "Musa Nnadi",
    },
    diagnosis: ["Routine postnatal monitoring"],
    medications: [
      { name: "Folic acid", dose: "5 mg", schedule: "Once daily" },
    ],
    labs: [
      { label: "Hemoglobin", value: "11.5 g/dL", updated: "Today" },
    ],
    sensitiveFields: {
      hivStatus: "Negative",
      mentalHealth: "No concerns",
      genotype: "AA",
    },
  },
];

export const AUDIT_EVENTS = [
  {
    id: 1,
    date: "12/09/2026",
    time: "19:36",
    actor: "Nurse",
    actorFullName: "Nurse Emeka Nwosu",
    actorId: "N8002",
    role: "NURSE",
    action: "Field accessed",
    field: "Allergies",
    target: "Fatima Abdullahi",
    ip: "192.168.1.50",
    eventId: "EVT320",
    hash: "7a1f32e14a91d4d47a7f32d47a7f32d4",
    prevHash: "1233d4432033034c1233d4432b3f...",
    chainOk: true,
  },
  {
    id: 2,
    date: "12/09/2026",
    time: "19:36",
    actor: "Nurse",
    actorFullName: "Nurse Emeka Nwosu",
    actorId: "N8002",
    role: "NURSE",
    action: "Viewed record",
    field: null,
    target: "Fatima Abdullahi",
    ip: "192.168.1.50",
    eventId: "EVT321",
    hash: "9b2e43f25b02e5e58b8f43e58b8f43e5",
    prevHash: "7a1f32e14a91d4d47a7f32d47a7f32d4",
    chainOk: true,
  },
  {
    id: 9,
    date: "08/09/2026",
    time: "08:43",
    actor: "Dr.",
    actorFullName: "Dr. Adaeze Okonkwo",
    actorId: "DR001",
    role: "ATTENDING_DOCTOR",
    action: "Viewed record",
    field: null,
    target: "Fatima Abdullahi",
    ip: "192.168.1.12",
    eventId: "EVT200",
    hash: "0295ba692c795a2c25f5ba2c25f5ba69",
    prevHash: "f184a9581b68419b14e4a9b14e4a958",
    chainOk: false,
  },
];

export const ROLE_PERMISSION_MATRIX = [
  { label: "Demographics", doctor: true, nurse: true, records: true, intern: true, it: false },
  { label: "Vitals", doctor: true, nurse: true, records: false, intern: false, it: false },
  { label: "Medications", doctor: true, nurse: true, records: false, intern: false, it: false },
  { label: "Allergies", doctor: true, nurse: true, records: false, intern: false, it: false },
  { label: "Clinical Notes", doctor: true, nurse: false, records: false, intern: false, it: false },
  { label: "HIV Status", doctor: true, nurse: false, records: false, intern: false, it: false },
  { label: "Mental Health Notes", doctor: true, nurse: false, records: false, intern: false, it: false },
  { label: "Genotype / Blood Group", doctor: true, nurse: false, records: false, intern: false, it: false },
];
